# Generated by Django 3.1.7 on 2021-03-31 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
                ('blade_number', models.CharField(max_length=200, null=True)),
                ('wtg_id', models.CharField(max_length=200, null=True)),
                ('set_nummber', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name_1', models.CharField(max_length=200, null=True)),
                ('company_1', models.CharField(max_length=200, null=True)),
                ('name_2', models.CharField(max_length=200, null=True)),
                ('company_2', models.CharField(max_length=200, null=True)),
                ('name_3', models.CharField(max_length=200, null=True)),
                ('company_3', models.CharField(max_length=200, null=True)),
                ('name_4', models.CharField(max_length=200, null=True)),
                ('company_4', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_id', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(choices=[('Leading Edge', 'Leading Edge'), ('Trailing Edge', 'Trailing Edge'), ('Preassure Side', 'Preassure Side'), ('Suction Side', 'Suction Side')], max_length=15, null=True)),
                ('description', models.CharField(choices=[('Root Coating', 'Root Coating'), ('Defect on Vortex Generators', 'Defect on Vortex Generators'), ('Pinhole', 'Pinhole'), ('Transport Damage', 'Transport Damage'), ('Chipped Paint', 'Chipped Paint'), ('Superficial Crack', 'Superficial Crack'), ('Erosion', 'Erosion'), ('Erosion with Exposed Laminate', 'Erosion with Exposed Laminate'), ('Ligthning Strike', 'Ligthning Strike'), ('Damaged Receptor', 'Damaged Receptor'), ('Drainhole', 'Drainhole')], max_length=30, null=True)),
                ('category', models.CharField(max_length=15, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('image_1', models.FileField(upload_to='images/')),
                ('image_2', models.FileField(upload_to='images/')),
                ('operation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='report.operation')),
            ],
        ),
    ]
