# Generated by Django 3.1.7 on 2021-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='company_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='company_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
