# Generated by Django 3.1.7 on 2021-04-01 10:53

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210331_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='image_1',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='image_2',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
